'use strict';
export const REQUEST_TRAILS = 'REQUEST_TRAILS';
export const RECEIVE_TRAILS = 'RECEIVE_TRAILS';
export const REQUEST_ANNOTATIONS = 'REQUEST_ANNOTATIONS';
export const RECEIVE_ANNOTATIONS = 'RECEIVE_ANNOTATIONS';
export const CACHE_LAST_ANNOTATION = 'CACHE_LAST_ANNOTATION'; 
export const CACHE_ANNOTATION = 'CACHE_ANNOTATION';
export const SEND_ANNOTATION = 'SEND_ANNOTATION'; 
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const REQUEST_PHOTO = 'REQUEST_PHOTO';
export const RECEIVE_PHOTO = 'RECEIVE_PHOTO';
export const SEND_PHOTO = 'SEND_PHOTO';
export const SEND_PHOTO_REPLY = 'SEND_PHOTO_REPLY';
export const CACHE_LAST_SAVED_PHOTO = 'CACHE_LAST_SAVED_PHOTO';
export const CURR_POSITION = 'CURR_POSITION';


