export const REQUEST_TRAILS = 'REQUEST_TRAILS';
export const RECEIVE_TRAILS = 'RECEIVE_TRAILS';
export const REQUEST_ANNOTATIONS = 'REQUEST_ANNOTATIONS';
export const RECEIVE_ANNOTATIONS = 'RECEIVE_ANNOTATIONS';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';